# configs/slam_common.yaml
noise:
  prior_xy:    0.05
  prior_theta: 0.02
  odom_xy:     0.08
  odom_theta:  0.015
  bearing:     0.0523599   # ≈3°
  range:       0.12
  inter_robot_xy: 0.15     # 若 GTSAM 不用可以忽略
  inter_robot_th: 0.03

obs:
  max_range:   20.0
  min_range:   0.1
  max_angle:   3.14159     # π，表示 360° 可视

anchor:
  add_anchor:      true
  anchor_strategy: "landmarks"  # landmarks / poses / mixed
